/* tslint:disable */
/* eslint-disable */
/**
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBagDto
 */
export interface CreateBagDto {
    /**
     * 
     * @type {number}
     * @memberof CreateBagDto
     */
    companyId: number;
}

/**
 * Check if a given object implements the CreateBagDto interface.
 */
export function instanceOfCreateBagDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "companyId" in value;

    return isInstance;
}

export function CreateBagDtoFromJSON(json: any): CreateBagDto {
    return CreateBagDtoFromJSONTyped(json, false);
}

export function CreateBagDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBagDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
    };
}

export function CreateBagDtoToJSON(value?: CreateBagDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'companyId': value.companyId,
    };
}

