/* tslint:disable */
/* eslint-disable */
/**
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCouponDto
 */
export interface CreateCouponDto {
    /**
     * 
     * @type {number}
     * @memberof CreateCouponDto
     */
    discountRate: number;
}

/**
 * Check if a given object implements the CreateCouponDto interface.
 */
export function instanceOfCreateCouponDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "discountRate" in value;

    return isInstance;
}

export function CreateCouponDtoFromJSON(json: any): CreateCouponDto {
    return CreateCouponDtoFromJSONTyped(json, false);
}

export function CreateCouponDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCouponDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discountRate': json['discountRate'],
    };
}

export function CreateCouponDtoToJSON(value?: CreateCouponDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discountRate': value.discountRate,
    };
}

