/* tslint:disable */
/* eslint-disable */
/**
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateBagDto,
} from '../models';
import {
    CreateBagDtoFromJSON,
    CreateBagDtoToJSON,
} from '../models';

export interface BagsControllerCreateRequest {
    createBagDto: CreateBagDto;
}

/**
 * 
 */
export class BagsApi extends runtime.BaseAPI {

    /**
     */
    async bagsControllerCreateRaw(requestParameters: BagsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createBagDto === null || requestParameters.createBagDto === undefined) {
            throw new runtime.RequiredError('createBagDto','Required parameter requestParameters.createBagDto was null or undefined when calling bagsControllerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bags`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBagDtoToJSON(requestParameters.createBagDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async bagsControllerCreate(requestParameters: BagsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.bagsControllerCreateRaw(requestParameters, initOverrides);
    }

}
