name: copy target.yml from repository1
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy target.yml
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone repository1
        uses: actions/checkout@v2
        with:
          repository: YukiHara1126/githubActions
          path: githubActions
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: copy target.yml
        run: cp -rp githubActions/typescript-fetch-client/ typescript-fetch-client/
      - name: clean githubActions
        run: rm -rf githubActions
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy target.yml'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated target.yml'